### ISSUE TITLE
Context based logging

### ISSUE THREAD

**Issue by nhooyr** [coder/slog#90]
https://www.komu.engineer/blogs/log-without-losing-context/log-without-losing-context

**Comment by gozeloglu** [comment]
Hi @nhooyr. It seems that [context support was added](https://github.com/coder/slog#:~:text=Full%20context.Context%20support) to pkg. Should this issue stay open? If I am missing something, please let me know.

**Comment by nhooyr** [comment]
Not sure, I no longer maintain this library so I'll go ahead and close.
